# Generated by Django 4.1.1 on 2022-11-09 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LogisticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('individual', 'INDIVIDUAL'), ('company', 'COMPANY')], max_length=20)),
                ('client_name', models.CharField(max_length=200)),
                ('client_address', models.TextField()),
                ('client_number', models.CharField(max_length=20)),
                ('retriever_type', models.CharField(choices=[('chemical', 'CHEMICAL'), ('perishable', 'PERISHABLE'), ('document', 'DOCUMENT'), ('others', 'OTHERS')], max_length=20)),
                ('retriever_name', models.CharField(max_length=200)),
                ('retriever_number', models.CharField(max_length=20)),
                ('retriever_address', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('individual', 'INDIVIDUAL'), ('company', 'COMPANY')], max_length=20)),
                ('weight', models.FloatField()),
                ('worth', models.FloatField()),
                ('mode', models.CharField(choices=[('freight', 'FREIGHT'), ('ship', 'SHIP'), ('land', 'LAND')], max_length=20)),
                ('tracking_id', models.CharField(blank=True, max_length=20)),
                ('tracking_pin', models.CharField(blank=True, max_length=20)),
                ('retrieval_id', models.CharField(blank=True, max_length=20)),
                ('collection_date', models.DateTimeField(auto_now_add=True)),
                ('departure_date', models.DateTimeField()),
                ('expected_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('retrieval_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentProgressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.logisticmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.countrymodel')),
            ],
        ),
    ]
