# Generated by Django 4.1.1 on 2022-11-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_countrymodel_logisticmodel_shipmentprogressmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentprogressmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentprogressmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('start', 'START'), ('progress', 'PROGRESS'), ('success', 'SUCCESS'), ('error', 'ERROR')], default='pending', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logisticmodel',
            name='item_type',
            field=models.CharField(choices=[('chemical', 'CHEMICAL'), ('perishable', 'PERISHABLE'), ('document', 'DOCUMENT'), ('others', 'OTHERS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logisticmodel',
            name='retriever_type',
            field=models.CharField(choices=[('individual', 'INDIVIDUAL'), ('company', 'COMPANY')], max_length=20),
        ),
    ]
