# Generated by Django 4.1.1 on 2022-11-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0003_shipmentprogressmodel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticmodel',
            name='destination',
            field=models.CharField(default='212 Lake Arena, Tinport Brazil', max_length=200),
            preserve_default=False,
        ),
    ]
