# Generated by Django 4.1.1 on 2022-11-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0006_shipmentprogressmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentprogressmodel',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='site_admin.logisticmodel'),
        ),
    ]
