# Generated by Django 4.1.1 on 2022-11-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSetupModel',
        ),
    ]
